<a href="https://colab.research.google.com/github/hrshwrdhn/ai_cheat/blob/main/L8_linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
list1 = [5, 6, 9]
vector1 = np.array(list1)
vector1_tensor = torch.from_numpy(vector1)


In [3]:
print(vector1_tensor)

tensor([5, 6, 9])


In [5]:
vector1_tensor_transpose = vector1_tensor.T

In [7]:
print(vector1_tensor_transpose)
print(vector1_tensor_transpose.shape)

tensor([5, 6, 9])
torch.Size([3])


In [9]:
list2 = [ [1,2,3],[4,5,6],[7,8,9] ]
matrix1 = np.array(list2)
matrix1_tensor = torch.from_numpy(matrix1)


transpose of a Tensor

In [13]:
matrix1_tensor_T =  matrix1_tensor.T
matrix1_tensor_T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [15]:
a = torch.tensor([2, 3])
b = torch.tensor([2, 1])
ab_dot = torch.dot(a,b)
ab_dot

tensor(7)

In [18]:
a = torch.tensor([[1,2,2,3], [0,2,3,4]])
b = torch.tensor([[1,0,0,3] ,[1,1,4,2]])
ab_dot = torch.dot(a,b)
ab_dot

RuntimeError: ignored

In [22]:
a = torch.tensor([2, 3])   # shape 1*2
b = torch.tensor([2, 1])   # shape 1*2
ab_mult = torch.matmul(a,b.T)   # (1*2) * (2*1) = 1*1
ab_mult

tensor(7)

In [24]:
tensor1 = torch.randn(3,2)
print(tensor1)
tensor2 = torch.randn(2,3)
print(tensor2)
tensor3 = torch.matmul(tensor1, tensor2)
print(tensor3)


tensor([[ 0.2276, -0.1756],
        [ 0.5550, -0.6630],
        [ 0.4650,  0.1725]])
tensor([[ 1.6544,  0.0409, -0.5078],
        [ 0.1644, -1.4861,  0.7449]])
tensor([[ 0.3477,  0.2702, -0.2464],
        [ 0.8093,  1.0080, -0.7757],
        [ 0.7977, -0.2374, -0.1076]])


# linear regression using pytorch inbuilds

In [25]:
import torch.nn as nn


In [26]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [28]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [29]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

# Dataset and DataLoader

We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch

In [ ]:
from torch.utils.data import TensorDataset

In [31]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
print(train_ds[0:3])

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]]))


The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [32]:
from torch.utils.data import DataLoader

In [33]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [34]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[103.,  43.,  36.],
        [ 73.,  66.,  44.],
        [ 91.,  87.,  65.],
        [ 92.,  87.,  64.],
        [ 91.,  88.,  64.]])
tensor([[ 20.,  38.],
        [ 57.,  69.],
        [ 80., 102.],
        [ 82., 100.],
        [ 81., 101.]])


In each iteration, the data loader returns one batch of data with the given batch size. If shuffle is set to True, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

# nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the nn.Linear class from PyTorch, which does it automatically.


In [36]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2249,  0.5072,  0.1317],
        [-0.5398,  0.0261,  0.1938]], requires_grad=True)
Parameter containing:
tensor([0.4338, 0.3816], requires_grad=True)


PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.


In [37]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2249,  0.5072,  0.1317],
         [-0.5398,  0.0261,  0.1938]], requires_grad=True),
 Parameter containing:
 tensor([0.4338, 0.3816], requires_grad=True)]

In [38]:
# Generate predictions
preds = model(inputs)
preds


tensor([[ 23.6623, -28.9437],
        [ 33.0310, -34.0429],
        [ 56.4696, -31.8451],
        [  4.1796, -46.3879],
        [ 42.8252, -20.7953],
        [ 22.9303, -29.5096],
        [ 32.6555, -33.8752],
        [ 56.3765, -32.1911],
        [  4.9116, -45.8220],
        [ 43.1818, -20.0617],
        [ 23.2869, -28.7760],
        [ 32.2990, -34.6088],
        [ 56.8451, -32.0127],
        [  3.8230, -47.1215],
        [ 43.5573, -20.2293]], grad_fn=<AddmmBackward>)

# Loss Function

Instead of defining a loss function manually, we can use the built-in loss function mse_loss.


In [39]:
# Import nn.functional
import torch.nn.functional as F

In [40]:
# Define loss function
loss_fn = F.mse_loss


In [41]:
loss = loss_fn(model(inputs), targets)
print(loss)


tensor(9281.1748, grad_fn=<MseLossBackward>)


# Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer optim.SGD. SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.


In [42]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Train the model

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions
2. Calculate the loss
3. Compute gradients w.r.t the weights and biases
4. Adjust the weights by subtracting a small quantity proportional to the gradient
5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function fit that trains the model for a given number of epochs.


In [43]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use opt.step to perform the update and opt.zero_grad to reset the gradients to zero.
* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. loss.item returns the actual value stored in the loss tensor.


In [44]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 106.8649
Epoch [20/100], Loss: 56.2532
Epoch [30/100], Loss: 40.9794
Epoch [40/100], Loss: 2.5284
Epoch [50/100], Loss: 14.5108
Epoch [60/100], Loss: 32.4683
Epoch [70/100], Loss: 10.1261
Epoch [80/100], Loss: 20.1472
Epoch [90/100], Loss: 16.8148
Epoch [100/100], Loss: 8.0918


In [45]:
# Generate predictions
preds = model(inputs)
preds


tensor([[ 57.6656,  70.9946],
        [ 80.0882,  99.2689],
        [121.1132, 134.4226],
        [ 24.5864,  40.9295],
        [ 96.3904, 114.5372],
        [ 56.4500,  69.9555],
        [ 79.5730,  99.1178],
        [121.2199, 134.9041],
        [ 25.8020,  41.9687],
        [ 97.0908, 115.4253],
        [ 57.1505,  70.8436],
        [ 78.8726,  98.2297],
        [121.6283, 134.5737],
        [ 23.8860,  40.0414],
        [ 97.6059, 115.5763]], grad_fn=<AddmmBackward>)

In [46]:
# Compare with targets
targets


tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])